# Generated by Django 3.2.7 on 2021-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('carcompany', models.CharField(max_length=20)),
                ('driveline', models.CharField(max_length=20)),
                ('geartype', models.CharField(max_length=20)),
            ],
        ),
    ]
